version: "3"

services:
  node:
    container_name: node-receitas
    build: .
    volumes:
      - ./:/home/greenwallet-node-receitas
    ports:
      - 3000:3000
    tty: true
    networks:
      greenwallet_net:
        ipv4_address: 10.5.0.5
    depends_on:
     - db

  db:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=receitas
      - MYSQL_USER='root'
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3310:3306
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
    container_name: db
    networks:
      greenwallet_net:
        ipv4_address: 10.5.0.6
        aliases:
          - greenwallet_network
        
volumes:
  my-db:

networks:
  greenwallet_net:
    name: greenwallet_net
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1